on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login to Docker hub"
        run: docker login --username abdohamed --password dckr_pat_A0Stz-lkwQzgw1eppFySwxswS2c
      # - name: "Building docker image"
      #   run: docker build -t ${{ secrets.DOCKER_USERNAME }}/3bdo .
      # - name: "Pushing to Docker hub"

      #
